import Link from 'next/link'
import { ArrowRight, BookOpen, Compass, Camera, Leaf } from 'lucide-react'
import { PageHero, SectionHeading, SiteShell } from '@/components/site-shell'

const guides = [
  ['Best time to visit East Africa','Planning','A month-by-month view of gorilla forests, savannah light and the great migration.','/images/sinza-zebra-family.jpg'],
  ['What to pack for a safari','Practical','A considered field list for rainforest trails, warm plains and cool camp mornings.','/images/sinza-lion-grass.jpg'],
  ['Gorilla trekking guide','Wildlife','What to expect in Bwindi, how to prepare and how to meet the forest respectfully.','/images/sinza-gorilla.jpg'],
  ['Chimpanzee tracking','Wildlife','Follow bright calls through Kibale, the primate capital of East Africa.','/images/sinza-baboon-forest.jpg'],
  ['Understanding the Big Five','Wildlife','Read the tracks, habitats and behaviour behind the safari shorthand.','/images/sinza-lion-walk.jpg'],
  ['Safari photography tips','Photography','Make space for the light with simple techniques from the back of the vehicle.','/images/sinza-baboon-monochrome.jpg'],
  ['Your first safari','Inspiration','The sounds, stillness and small surprises that make a day in the wild.','/images/sinza-boat-safari.jpg'],
  ['Responsible tourism','Conservation','Travel with care for the wildlife, communities and places that welcome you.','/images/sinza-baboon-family.jpg'],
]
export default function SafariIntelPage() { return <SiteShell><main><PageHero eyebrow="Safari Intel · The field journal" title={<>Good to know<br /><em>before you go.</em></>} intro="A practical, visual guide to travelling well through East Africa — from the first question to the final campfire." image="/images/sinza-giraffe-landscape.jpg" /><section className="intel-intro section-wrap"><div className="intel-intro-mark"><BookOpen size={28}/><span>Field notes<br/>for curious travellers</span></div><SectionHeading eyebrow="Safari planning guides" title={<>The details<br /><em>that matter.</em></>} intro="Useful answers, honest context and inspiration from a team that lives close to the ground." /><div className="intel-library">{guides.map(([title, category, copy, image]) => <Link href="/contact" className="intel-feature-card" key={title}><div className="intel-feature-image"><img src={image} alt={title}/><span className="intel-hover-label">Read guide <ArrowRight size={14}/></span></div><div className="intel-card-copy"><p className="eyebrow">{category}</p><h3>{title}</h3><p>{copy}</p><span className="text-link">Explore the field notes <ArrowRight size={14}/></span></div></Link>)}</div></section><section className="intel-country-band"><div><p className="eyebrow">Know the country</p><h2>Four countries.<br/><em>One extraordinary region.</em></h2></div><div className="country-pills"><Link href="/destinations/uganda">Uganda <ArrowRight size={14}/></Link><Link href="/destinations/rwanda">Rwanda <ArrowRight size={14}/></Link><Link href="/destinations/kenya">Kenya <ArrowRight size={14}/></Link><Link href="/destinations/tanzania">Tanzania <ArrowRight size={14}/></Link></div></section></main></SiteShell> }
