import Link from 'next/link'
import { ArrowRight, CalendarDays, Check, Heart, Sparkles, Users } from 'lucide-react'
import { SiteShell, PageHero, EnquiryCta } from '@/components/site-shell'

const offers = [
  ['Gorilla & Chimpanzee Trekking', 'Bwindi & Kibale · Uganda', 'Two extraordinary forests, guided with care: mountain gorillas in Bwindi and chimpanzees in Kibale.', '/images/sinza-gorilla.jpg', '7 days', 'Primate journey'],
  ['Big Five Game Drives', 'Murchison Falls · Queen Elizabeth · Kidepo', 'A classic Uganda circuit with wide savannah, tree-climbing lions, elephants and dramatic wilderness.', '/images/sinza-lion-walk.jpg', '10 days', 'Wildlife journey'],
  ['Birding Safari', 'Uganda · 1,000+ recorded species', 'Patient, expertly guided birding across wetlands, forest and savannah for both specialist and curious birders.', '/images/sinza-giraffe-landscape.jpg', '8 days', 'Birding journey'],
  ['Nile Boat Cruises', 'Murchison Falls & Jinja', 'Spot hippos, crocodiles and waterbirds from the river, with peaceful time on Uganda’s life-giving waterways.', '/images/sinza-boat-safari.jpg', '5 days', 'River journey'],
  ['Honeymoon Safaris', 'Private lodges · Scenic views', 'Romantic escapes with slow mornings, private stays, golden-hour drives and space to celebrate together.', '/images/sinza-zebra-family.jpg', '8 days', 'Romantic journey'],
  ['Team Building Trips', 'For organisations, NGOs, churches & schools', 'Purposeful group journeys that bring people together through nature, culture and shared adventure.', '/images/sinza-baboon-family.jpg', 'Flexible', 'Group journey'],
  ['Multi-Country Tours', 'Uganda · Rwanda · Kenya · Tanzania', 'Add a neighbouring country to your itinerary for a richer East African story and a seamless private route.', '/images/sinza-gorilla.jpg', '10+ days', 'East Africa journey'],
  ['Adventure Add-Ons', 'Hiking · Rafting · Zip-lining & more', 'Build in an active day on the Nile, in the hills or above the forest canopy when you want extra energy.', '/images/sinza-lion-grass.jpg', 'From 1 day', 'Adventure journey'],
  ['Cultural & Community Tours', 'Eastern Uganda · Busoga Kingdom', 'Village walks, school visits, cultural performances, workshops, home visits and local meals with respect.', '/images/sinza-baboon-forest.jpg', '3–6 days', 'Culture journey'],
]

export default function OffersPage() { return <SiteShell><main><PageHero eyebrow="Special offers · Uganda first" title={<>More ways to<br/><em>go deeper.</em></>} intro="Start with Uganda’s forests, rivers, savannahs and communities. Then shape the route around the people, places and moments that matter to you." image="/images/sinza-gorilla.jpg"/><section className="offers-stage section-wrap"><div className="offers-heading"><div><p className="eyebrow">Our Uganda journeys</p><h2>Begin here.<br/><em>Go further.</em></h2></div><p>From gorilla trekking to the Source of the Nile, we design private journeys with trusted local guides and room for discovery.</p></div><div className="offer-grid premium-offer-grid">{offers.map(([title,destination,copy,image,days,badge],index)=><article className="premium-offer-card" key={title}><div className="offer-image"><img src={image} alt={title}/><span className="offer-badge">{title.includes('Honeymoon') ? <Heart size={13}/> : title.includes('Team') ? <Users size={13}/> : <Sparkles size={13}/>} {badge}</span><span className="offer-number">{String(index+1).padStart(2,'0')}</span></div><div className="offer-copy"><p className="eyebrow">{destination}</p><h3>{title}</h3><p>{copy}</p><div className="offer-meta"><span><CalendarDays size={14}/>{days}</span><strong>Private</strong></div><div className="offer-included"><span><Check size={13}/> Local planning</span><span><Check size={13}/> Trusted guides</span><span><Check size={13}/> Flexible pace</span></div><Link href="/contact" className="button dark">Start a conversation <ArrowRight size={15}/></Link></div></article>)}</div></section><section className="eastern-uganda section-wrap"><div className="offers-heading"><div><p className="eyebrow">Discover Eastern Uganda</p><h2>Beauty, history<br/><em>& hidden treasures.</em></h2></div><p>Often overlooked, Eastern Uganda offers incredible culture, scenery and spiritual depth. Let us guide you through a region rich with meaning.</p></div><div className="eastern-grid"><div><img src="/images/sinza-boat-safari.jpg" alt="Family boat cruise on the Nile in Uganda"/></div><div className="eastern-list">{['Kagulu Hill — Climb sacred rocks for panoramic views','Source of the Nile — Explore the beginning of the world’s longest river','Ssezibwa Falls — A spiritual and natural sanctuary','Lake Bunyonyi — Serene, scenic and perfect for reflection','Busoga Kingdom Tour — Discover royal heritage and cultural traditions'].map((item)=><div key={item}><Check size={15}/><p>{item}</p></div>)}</div></div></section><EnquiryCta/></main></SiteShell> }
