import Link from 'next/link'
import { notFound } from 'next/navigation'
import { ArrowRight } from 'lucide-react'
import { destinationDetails, destinations, destByRegion } from '@/lib/safari-data'
import { SiteShell, EnquiryCta, SectionHeading } from '@/components/site-shell'

const parkDetails: Record<string, { overview: string; wildlife: string; activities: string; planning: string }> = {
  bwindi: { overview: 'Bwindi Impenetrable National Park is an ancient montane rainforest in south-west Uganda and a UNESCO World Heritage Site. Its steep paths, dense vegetation and misty valleys protect one of the world’s most important mountain gorilla habitats.', wildlife: 'Mountain gorillas are the signature encounter, alongside forest elephants, golden cats, colobus monkeys, chimpanzees, birds and many rare Albertine Rift species.', activities: 'Gorilla trekking, gorilla habituation experiences, guided forest walks, birding and community visits with Batwa and neighbouring communities.', planning: 'Gorilla permits are limited and should be secured early. The terrain is steep and wet; sturdy boots, layered clothing and physical preparation are essential.' },
  kibale: { overview: 'Kibale National Park protects one of Africa’s finest remaining tracts of lowland and montane rainforest. It is known for its rich primate diversity and shaded forest trails.', wildlife: 'Chimpanzees are the headline species, with red colobus, black-and-white colobus, L’Hoest’s monkeys, mangabeys, forest elephants and exceptional birdlife.', activities: 'Chimpanzee tracking, chimpanzee habituation, Bigodi Wetland walks, birding and guided nature walks.', planning: 'Morning tracking starts early. Comfortable walking shoes, long sleeves, insect repellent and rain protection make forest days more enjoyable.' },
  'queen-elizabeth': { overview: 'Queen Elizabeth National Park spans open savannah, crater lakes, woodland and the Kazinga Channel in western Uganda.', wildlife: 'Expect elephants, buffaloes, hippos, crocodiles, leopards, lions, antelopes and the famous tree-climbing lions of Ishasha.', activities: 'Game drives, Kazinga Channel boat cruises, crater-lake visits, mongoose tracking and Ishasha wildlife viewing.', planning: 'Wildlife viewing is best in the early morning and late afternoon. A boat cruise adds a different perspective and excellent bird and hippo sightings.' },
  'murchison-falls': { overview: 'Murchison Falls National Park is Uganda’s largest protected area, shaped by the Victoria Nile as it forces through a narrow gorge before plunging over the falls.', wildlife: 'The park supports elephants, giraffes, buffaloes, lions, leopards, hartebeest, hippos, crocodiles and abundant waterbirds.', activities: 'Northern-sector game drives, Victoria Nile launch cruises, hiking to the Top of the Falls and rhino tracking at nearby Ziwa.', planning: 'Dry seasons generally offer easier roads and concentrated wildlife. A full route usually needs at least two nights to combine drives and the river.' },
  kidepo: { overview: 'Kidepo Valley National Park is a remote wilderness in north-eastern Uganda, framed by the Kidepo and Narus valleys and the rugged mountains of Karamoja.', wildlife: 'Lions, cheetahs, leopards, elephants, buffaloes, zebras, giraffes, hartebeest and rare dry-country species thrive in its open valleys.', activities: 'Game drives in the Narus and Kidepo valleys, scenic viewpoints and respectful cultural encounters with local communities.', planning: 'The park is remote and transfers are long, so fly-in or extended road itineraries work best. Pack for heat, dust and limited services.' },
  rwenzori: { overview: 'Rwenzori Mountains National Park protects the legendary Mountains of the Moon, with dramatic valleys, alpine vegetation, waterfalls and high peaks.', wildlife: 'Forest and montane habitats hold colobus monkeys, hyrax, duikers, elephants and a remarkable range of Albertine Rift birds and plants.', activities: 'Multi-day mountain trekking, guided nature walks, birding, waterfalls and cultural experiences in surrounding communities.', planning: 'Routes are physically demanding and weather can change quickly. Use an experienced mountain team and allow time for acclimatisation.' },
  mgahinga: { overview: 'Mgahinga Gorilla National Park protects Uganda’s section of the Virunga range, where three volcanic peaks rise above bamboo and montane forest.', wildlife: 'The park is home to habituated mountain gorillas, golden monkeys, buffaloes, elephants and rich highland birdlife.', activities: 'Gorilla trekking, golden monkey tracking, volcano hiking, the Batwa trail and guided forest walks.', planning: 'Permits are limited and the volcanic terrain is steep. Pack waterproof layers, sturdy boots and allow time for a full trekking day.' },
  semuliki: { overview: 'Semuliki National Park lies in the floor of the Albertine Rift and protects Uganda’s only true lowland tropical forest.', wildlife: 'Expect Central African forest species, primates, forest elephants, duikers, butterflies and an exceptional list of forest and wetland birds.', activities: 'Sempaya hot springs, guided forest walks, birding, primate viewing and cultural encounters with communities around the park.', planning: 'The lowland forest is warm and humid. Carry drinking water, rain protection, insect repellent and binoculars.' },
  'mount-elgon': { overview: 'Mount Elgon National Park surrounds an ancient extinct volcano on Uganda’s eastern border, with a vast caldera, cliffs, caves and waterfalls.', wildlife: 'The montane forest supports buffaloes, elephants, duikers, primates and many high-altitude birds and plants.', activities: 'Multi-day hiking, waterfalls, caves, the caldera, coffee-region visits and guided birding.', planning: 'Hikes vary from gentle walks to demanding summit routes. Weather changes quickly, so use a registered guide and pack warm waterproof layers.' },
  volcanoes: { overview: 'Volcanoes National Park protects Rwanda’s Virunga volcanoes and the high-altitude rainforest where mountain gorillas and golden monkeys live.', wildlife: 'Mountain gorillas, golden monkeys, buffaloes, forest elephants and distinctive highland birds are among the park’s highlights.', activities: 'Gorilla trekking, golden monkey tracking, volcano hikes, Dian Fossey site visits and guided forest walks.', planning: 'Permits are limited. The altitude and steep terrain require preparation, waterproof layers and good walking shoes.' },
  akagera: { overview: 'Akagera National Park is Rwanda’s eastern savannah reserve, a mosaic of grassland, woodland, lakes and papyrus wetlands along the Tanzanian border.', wildlife: 'Elephants, buffaloes, giraffes, zebras, antelopes, lions, leopards, hippos, crocodiles and abundant birds can be found here.', activities: 'Game drives, boat trips on Lake Ihema, birding and sunset or night drives where available.', planning: 'Early starts give the best wildlife viewing. Combine a boat trip with game drives for a fuller picture of the park.' },
  nyungwe: { overview: 'Nyungwe Forest National Park is one of Africa’s oldest rainforests, a vast highland forest of ridges, ravines, waterfalls and exceptional biodiversity.', wildlife: 'Chimpanzees, colobus monkeys, mangabeys, forest birds and many endemic plants make Nyungwe a major primate and biodiversity destination.', activities: 'Chimpanzee tracking, canopy walks, colobus tracking, birding, waterfall hikes and forest nature trails.', planning: 'Forest weather is changeable and trails can be slippery. Plan an early start and bring waterproof clothing, sturdy shoes and binoculars.' },
  'lake-kivu': { overview: 'Lake Kivu and Rubavu offer a relaxed lakeside counterpoint to Rwanda’s forests and savannah, with volcanic hills meeting deep, clear water.', wildlife: 'The lake is known for waterbirds, fish and scenic landscapes rather than big-game viewing, with rich cultural life along the shore.', activities: 'Boat rides, kayaking, lakeside walks, coffee experiences, cycling and scenic drives around the hills.', planning: 'It is an excellent rest or extension destination before or after gorilla trekking. Mornings are often clearest for lake views.' },
}
export function generateStaticParams() { return [...destinations.map((item) => item.slug), ...destinationDetails.map((item) => item.slug)].map((slug) => ({ slug })) }
export default async function DestinationDetail({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const place = destinations.find((item) => item.slug === slug); const country = destinationDetails.find((item) => item.slug === slug); if (!place && !country) notFound(); const title = place?.name ?? country!.name; const image = place?.image ?? country!.image; const intro = place?.description ?? country!.copy; const park = place ? parkDetails[place.slug] : undefined; return <SiteShell><main><section className="detail-hero"><img src={image} alt={title} /><div><p className="eyebrow">{place?.region ?? country?.tagline}</p><h1>{title}</h1><p>{intro}</p><Link href="/safaris" className="button light">Find safaris here <ArrowRight size={16} /></Link></div></section>{park && <section className="section-wrap park-detail-grid"><div><p className="eyebrow">About the park</p><h2>Know the<br /><em>landscape.</em></h2><p>{park.overview}</p></div><div className="park-detail-card"><h3>Wildlife</h3><p>{park.wildlife}</p><h3>Things to do</h3><p>{park.activities}</p><h3>Planning notes</h3><p>{park.planning}</p></div></section>}<section className="section-wrap detail-layout"><article><p className="eyebrow">A sense of place</p><h2>Come for the<br /><em>landscape.</em></h2><p className="large-copy">Spend time looking closely: follow the light, listen for forest calls and let local stories add depth to the view. We will help you choose the right season, route and stays for this part of East Africa.</p></article><aside className="detail-aside"><p className="eyebrow">Best time to visit</p><p className="season-copy">{place?.best ?? 'A considered route can work throughout the year, with each season bringing a different texture to the landscape.'}</p><p className="eyebrow aside-label">Plan your route</p><p className="section-intro">Pair {title} with another region for a private journey shaped around your interests.</p><Link className="text-link" href="/contact">Plan this destination <ArrowRight size={16} /></Link></aside></section><section className="section-wrap"><SectionHeading eyebrow="Keep exploring" title={<>More places<br /><em>to discover.</em></>} /><div className="destination-grid">{(country ? (destByRegion.Rwanda ?? []).map((item) => destinations.find((destination) => destination.slug === item.slug)).filter((item): item is (typeof destinations)[number] => Boolean(item)) : destinations.filter((item) => item.slug !== slug).slice(0, 3)).map((item) => <Link href={`/destinations/${item.slug}`} className="destination-card" key={item.slug}><img src={item.image} alt={item.name} /><div><p>{item.region}</p><h3>{item.name}</h3></div></Link>)}</div></section><EnquiryCta /></main></SiteShell> }
