'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { ArrowDownRight, ArrowRight, Check, ChevronDown, Search } from 'lucide-react'
import { safaris, articles, type Safari } from '@/lib/safari-data'

export function HeroCarousel() { const slides = [{ image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1800&q=90', caption: 'Meaningful journeys across East Africa' }, { image: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=1800&q=90', caption: 'Into ancient forests' }, { image: 'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=1800&q=90', caption: 'Wildlife, your way' }]; const [active, setActive] = useState(0); useEffect(() => { const timer = window.setInterval(() => setActive((value) => (value + 1) % slides.length), 6000); return () => window.clearInterval(timer) }, [slides.length]); return <div className="hero-image"><img src={slides[active].image} alt={slides[active].caption} /><span className="image-caption">{slides[active].caption}</span><div className="hero-controls"><button aria-label="Previous hero image" onClick={() => setActive((active + slides.length - 1) % slides.length)}>←</button>{slides.map((slide, index) => <button aria-label={`Show hero image ${index + 1}`} className={active === index ? 'active' : ''} key={slide.image} onClick={() => setActive(index)} />)}<button aria-label="Next hero image" onClick={() => setActive((active + 1) % slides.length)}>→</button></div></div> }

export function SafariGrid({ items = safaris }: { items?: Safari[] }) { return <div className="safari-grid">{items.map((safari, index) => <article className="safari-card" key={safari.slug}><Link className="card-image" href={`/safaris/${safari.slug}`}><img src={safari.image} alt={safari.title} /><span className="card-index">0{index + 1}</span><span className="card-arrow"><ArrowDownRight /></span></Link><div className="card-meta"><span>{safari.duration}</span><span>{safari.category}</span></div><h3>{safari.title}</h3><p>{safari.summary}</p><Link className="card-link" href={`/safaris/${safari.slug}`}>View journey <ArrowRight size={15} /></Link></article>)}</div> }

export function SafariExplorer() { const [query, setQuery] = useState(''); const [category, setCategory] = useState('All'); const categories = ['All', ...Array.from(new Set(safaris.map((item) => item.category)))]; const filtered = useMemo(() => safaris.filter((item) => (category === 'All' || item.category === category) && `${item.title} ${item.summary}`.toLowerCase().includes(query.toLowerCase())), [category, query]); return <><div className="explorer-controls"><label className="search-box"><Search size={16} /><input aria-label="Search safaris" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search journeys" /></label><div className="filter-row">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={category === item ? 'filter active' : 'filter'}>{item}</button>)}</div></div>{filtered.length ? <SafariGrid items={filtered} /> : <div className="empty-state"><h3>No journey found.</h3><p>Try another destination, experience or category.</p></div>}</> }

export function FaqList({ items }: { items: string[] }) { const [active, setActive] = useState<number | null>(null); return <div className="faq-list">{items.map((item, index) => <button className="faq-item" key={item} onClick={() => setActive(active === index ? null : index)}><span>{item}</span>{active === index ? <ChevronDown /> : <ArrowRight />}{active === index && <p>Our journey designers will talk through the details with you, then provide a considered itinerary, accommodation options and transparent next steps.</p>}</button>)}</div> }

export function EnquiryWizard() { const [step, setStep] = useState(1); const [done, setDone] = useState(false); const next = () => setStep((value) => Math.min(value + 1, 5)); return <div className="wizard">{done ? <div className="form-success"><Check size={28} /><h3>Thank you for reaching out.</h3><p>We&apos;ve received your enquiry and will be in touch with thoughtful ideas within 24 hours.</p><button className="button dark" onClick={() => { setDone(false); setStep(1) }}>Send another enquiry</button></div> : <><div className="wizard-progress">{['Where','When','Who','Budget','You'].map((label, index) => <span className={step >= index + 1 ? 'active' : ''} key={label}>0{index + 1} {label}</span>)}</div>{step === 1 && <div className="wizard-fields"><h3>Where are you dreaming of?</h3><p className="section-intro">Pick one or more. We&apos;ll tailor the route around your choices.</p><label>Destination<select defaultValue=""><option value="" disabled>Select a destination</option><option>Uganda</option><option>Uganda & Rwanda</option><option>Kenya & Tanzania</option><option>Multi-country East Africa</option></select></label><button className="button dark" onClick={next}>Continue <ArrowRight size={16} /></button></div>}{step === 2 && <div className="wizard-fields"><h3>When would you like to travel?</h3><label>Preferred month<input type="month" /></label><label>Trip length<input placeholder="e.g. 10 days" /></label><button className="button dark" onClick={next}>Continue <ArrowRight size={16} /></button></div>}{step === 3 && <div className="wizard-fields"><h3>Who are you travelling with?</h3><label>Travellers<select defaultValue=""><option value="" disabled>Select group size</option><option>Just me</option><option>Two travellers</option><option>Family</option><option>Friends or group</option></select></label><label>Interests<input placeholder="Gorillas, wildlife, culture, photography..." /></label><button className="button dark" onClick={next}>Continue <ArrowRight size={16} /></button></div>}{step === 4 && <div className="wizard-fields"><h3>What feels comfortable?</h3><label>Approximate budget<select defaultValue=""><option value="" disabled>Select a range</option><option>Under $3,000 per person</option><option>$3,000–$6,000 per person</option><option>$6,000+ per person</option><option>Let&apos;s discuss</option></select></label><button className="button dark" onClick={next}>Continue <ArrowRight size={16} /></button></div>}{step === 5 && <div className="wizard-fields"><h3>Tell us about your journey</h3><label>Your name<input required placeholder="Your name" /></label><label>Email address<input required type="email" placeholder="you@example.com" /></label><label>A little more<textarea rows={4} placeholder="What would make this trip meaningful for you?" /></label><button className="button dark" onClick={() => setDone(true)}>Send enquiry <ArrowRight size={16} /></button></div>}</>}</div> }

export function GalleryGrid({ images }: { images: { src: string; alt: string; label: string }[] }) { const [active, setActive] = useState<number | null>(null); return <><div className="gallery-grid">{images.map((image, index) => <button className={`gallery-tile gallery-tile-${index % 5}`} key={image.src} onClick={() => setActive(index)}><img src={image.src} alt={image.alt} /><span>{image.label}</span></button>)}</div>{active !== null && <div className="lightbox" role="dialog" aria-label="Gallery image" onClick={() => setActive(null)}><button className="lightbox-close" aria-label="Close image" onClick={() => setActive(null)}>×</button><img src={images[active].src} alt={images[active].alt} onClick={(event) => event.stopPropagation()} /></div>}</> }

export function ArticleFilter() { const [filter, setFilter] = useState('All'); const cats = ['All', ...Array.from(new Set(articles.map((article) => article.category)))]; const visible = filter === 'All' ? articles : articles.filter((article) => article.category === filter); return <><div className="filter-row">{cats.map((cat) => <button key={cat} className={filter === cat ? 'filter active' : 'filter'} onClick={() => setFilter(cat)}>{cat}</button>)}</div><div className="article-grid">{visible.map((article) => <Link className="article-card" key={article.slug} href={`/blog/${article.slug}`}><img src={article.image} alt="" /><div><p className="eyebrow">{article.category}</p><h3>{article.title}</h3><p>{article.excerpt}</p><span className="card-link">Read story <ArrowRight size={15} /></span></div></Link>)}</div></> }
