import Link from 'next/link'
import { ArrowRight } from 'lucide-react'
import { notFound } from 'next/navigation'
import { SiteShell, PageHero, EnquiryCta } from '@/components/site-shell'
import { ItineraryAccordion } from '@/components/itinerary-accordion'
import { journeyCountries, getSafari } from '@/lib/safari-data'

export function generateStaticParams() { return [...journeyCountries.map((country) => ({ slug: country.slug })), ...journeyCountries.flatMap((country) => country.journeys.map((journey) => ({ slug: journey.slug })))] }

function itineraryForCatalogJourney(title: string, duration: string) {
  const days = Number.parseInt(duration, 10)
  const dayPlans: Record<string, { title: string; details: string[] }[]> = {
    '1 Day Ziwa Rhino Tracking Tour': [{ title: 'Ziwa Rhino Sanctuary', details: ['Travel to Ziwa Rhino Sanctuary with your guide.', 'Track southern white rhinos on foot with a trained ranger.', 'Learn about rhino conservation before returning to Kampala or Entebbe.'] }],
    '2 Days Murchison Falls': [{ title: 'Travel to Murchison Falls', details: ['Travel north from Kampala or Entebbe to Murchison Falls National Park.', 'Settle into your lodge and enjoy the park surroundings.'] }, { title: 'Game Drive, Nile Cruise and Departure', details: ['Take a morning game drive in the northern sector.', 'Cruise the Victoria Nile towards the base of Murchison Falls.', 'Visit the Top of the Falls before beginning the return journey.'] }],
    '3 Days Bwindi Gorilla Trekking': [{ title: 'Travel to Bwindi', details: ['Travel through Uganda’s south-western landscapes to Bwindi Impenetrable Forest.', 'Check in at your forest-edge lodge.'] }, { title: 'Gorilla Trekking', details: ['Attend the park briefing and trek into Bwindi with ranger guides.', 'Spend one hour observing a habituated gorilla family.'] }, { title: 'Community Visit and Departure', details: ['Enjoy breakfast and a local community or craft experience.', 'Transfer onward to Kampala, Entebbe or Kigali.'] }],
    '5 Days Murchison Falls & Queen Elizabeth': [{ title: 'Travel to Murchison Falls', details: ['Travel north from Kampala or Entebbe and settle near the park.'] }, { title: 'Murchison Falls Wildlife', details: ['Take a northern-sector game drive and look for elephants, giraffes, buffaloes and lions.', 'Enjoy a Victoria Nile boat cruise.'] }, { title: 'Top of the Falls and Transfer', details: ['Visit the Top of Murchison Falls.', 'Travel south towards Queen Elizabeth National Park.'] }, { title: 'Queen Elizabeth Safari', details: ['Take a Kasenyi plains game drive.', 'Cruise the Kazinga Channel among hippos, crocodiles and birdlife.'] }, { title: 'Return Journey', details: ['Enjoy a final morning activity before travelling back to Kampala or Entebbe.'] }],
    '5 Days Gorillas & Lions Tracking': [{ title: 'Travel to Queen Elizabeth', details: ['Travel west through Uganda to Queen Elizabeth National Park.'] }, { title: 'Ishasha Tree-Climbing Lions', details: ['Explore the Ishasha sector and search for its famous tree-climbing lions.'] }, { title: 'Transfer to Bwindi', details: ['Drive through the Albertine Rift to Bwindi Impenetrable Forest.', 'Settle into your lodge.'] }, { title: 'Gorilla Trekking', details: ['Complete the park briefing and trek to a habituated gorilla family.'] }, { title: 'Community Visit and Departure', details: ['Visit a local community or craft project before your onward transfer.'] }],
  }
  const planned = dayPlans[title]
  if (planned) return planned.map((day, index) => ({ day: `Day ${index + 1}`, ...day }))
  const route = title.toLowerCase()
  const places = route.includes('kidepo') ? 'Kidepo Valley and the Karamoja region' : route.includes('murchison') ? 'Murchison Falls and the Victoria Nile' : route.includes('bwindi') || route.includes('gorilla') ? 'Bwindi Impenetrable Forest' : route.includes('rwanda') || route.includes('volcanoes') ? 'Rwanda’s volcanoes and rainforest' : route.includes('waterfall') || route.includes('sipi') ? 'Eastern Uganda’s waterfalls, hills and coffee country' : 'Uganda’s forests, savannah and local communities'
  return Array.from({ length: days }, (_, index) => ({ day: `Day ${index + 1}`, title: index === 0 ? `Arrival and journey briefing` : index === days - 1 ? 'Final experience and departure' : `Explore ${places}`, details: index === 0 ? [`Meet your Sinza guide at the agreed pickup point and review the route, driving times, permits and any dietary or mobility needs.`, `Travel towards ${places}, with scenic stops, lunch and an introduction to the communities and landscapes along the way.`, 'Check in at the night’s accommodation, settle in and receive a briefing for the following day.'] : index === days - 1 ? [`Enjoy breakfast and a final guided activity according to your departure time.`, 'Review photographs, local crafts and any final purchases with your guide.', 'Transfer to Kampala, Kigali, Entebbe or the next agreed stop; your guide remains with you until handover.'] : [`Start early when wildlife is most active and follow your ranger or specialist guide through ${places}.`, 'Allow time for the full experience rather than rushing between viewpoints: tracks, calls, plants, landscapes and local stories are all part of the day.', 'Return for lunch and a rest period, then continue with an afternoon activity, game drive, boat cruise or community visit.', 'Dinner and overnight at your lodge or camp, with the next day’s meeting time confirmed before bed.'] }))
}

export default async function SafariDetail({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const country = journeyCountries.find((item) => item.slug === slug)
  if (country) return <SiteShell><main><PageHero eyebrow="Our journeys" title={country.name} intro={`${country.tagline}. Discover journeys shaped around wildlife, landscape, culture and time.`} image={country.image} /><section className="section-wrap"><div className="section-heading"><div><p className="eyebrow">{country.name} Safaris</p><h2>Choose your way in.</h2></div><p>Every route can be extended, slowed down or made entirely your own. Open any itinerary for the full route, highlights and day-by-day plan.</p></div><div className="journey-country-list">{country.journeys.map((journey) => <article className="journey-country-card" key={journey.slug}><img src={journey.image} alt={journey.title} /><div><p className="eyebrow">{journey.duration}</p><h3>{journey.title}</h3><p>{`A guided ${journey.duration.split(' / ')[0]} journey through ${country.name}, combining wildlife, landscapes and local experiences.`}</p><Link className="button dark" href={`/safaris/${journey.slug}`}>View full itinerary <ArrowRight size={16} /></Link></div></article>)}</div></section><EnquiryCta /></main></SiteShell>
  const safari = getSafari(slug)
  const catalogJourney = journeyCountries.flatMap((item) => item.journeys).find((item) => item.slug === slug)
  if (!safari && !catalogJourney) notFound()
  const journeyCountry = journeyCountries.find((item) => item.journeys.some((journey) => journey.slug === slug))?.name ?? 'Uganda'
  const detailBase = safari ?? { ...catalogJourney!, category: `${journeyCountry} Safaris`, summary: `${catalogJourney!.title} is a thoughtfully paced journey combining the places and experiences named in the itinerary. Expect expert guiding, comfortable stays and time to experience each destination properly.`, destinations: catalogJourney!.title.split(/ & | and |, /).slice(0, 4), highlights: ['Expert local guiding throughout', 'Wildlife, landscapes and local culture', `Signature experiences from the ${catalogJourney!.title} route`, 'Comfortable accommodation and flexible pacing'], itinerary: undefined }
  const detail = { ...detailBase, itinerary: detailBase.itinerary?.length ? detailBase.itinerary : itineraryForCatalogJourney(detailBase.title, detailBase.duration) }
  return <SiteShell><main><section className="detail-hero"><img src={detail.image} alt={detail.title} /><div><p className="eyebrow">{detail.duration} · {detail.category}</p><h1>{detail.title}</h1><p>{detail.summary}</p><Link href="/contact" className="button light">Enquire about this journey <ArrowRight size={16} /></Link></div></section><section className="section-wrap detail-layout"><article><p className="eyebrow">The journey</p><h2>Made around<br /><em>you.</em></h2><p className="large-copy">This considered itinerary brings together remarkable landscapes with the time and flexibility to experience them properly. Speak with our local journey designers to shape the route, lodge style and pace.</p></article><aside className="detail-aside"><p className="eyebrow">Highlights</p>{detail.highlights.map((highlight) => <p className="highlight" key={highlight}>{highlight}</p>)}</aside></section>{detail.itinerary && <section className="section-wrap itinerary-section"><div className="section-heading"><div><p className="eyebrow">Itinerary</p><h2>Day by day.</h2></div></div><ItineraryAccordion days={detail.itinerary} /></section>}<EnquiryCta /></main></SiteShell>
}
