import { ArrowRight, Compass, MessageCircle, Route, Sparkles, Users } from 'lucide-react'
import { SiteShell, PageHero, EnquiryCta } from '@/components/site-shell'

const steps = [
  ['01', 'Listen deeply', 'We start with your people, your pace and the feeling you want to take home. No form answers the important questions, so we make room for a real conversation.', MessageCircle],
  ['02', 'Read the landscape', 'Our Uganda-based team brings together seasons, permits, roads, wildlife movement, lodges and local relationships to find the right route.', Compass],
  ['03', 'Shape the rhythm', 'You receive a considered proposal with choices, not a sales pitch. We refine the route until it feels like yours, down to the pauses between highlights.', Route],
  ['04', 'Travel with confidence', 'Your guide is close, the details are clear and we stay available throughout. You can be spontaneous because the foundations are well cared for.', Users],
]

export default function HowWeWorkPage() { return <SiteShell><main><PageHero eyebrow="Our approach" title={<>The route starts<br /><em>with listening.</em></>} intro="Thoughtful planning, local expertise and a journey that never feels like somebody else&apos;s." image="/images/sinza-lion-walk.jpg" /><section className="work-intro section-wrap"><p className="eyebrow">A different kind of planning</p><h2>Less ticking boxes.<br /><em>More feeling the place.</em></h2><p>We believe the best safari is built in conversation. Our job is to make the complex feel simple, then leave enough space for the unexpected.</p></section><section className="work-steps">{steps.map(([number, title, copy, Icon]) => { const StepIcon = Icon as typeof MessageCircle; return <article key={number}><div className="work-step-icon"><StepIcon /></div><span>{number}</span><h2>{title as string}</h2><p>{copy as string}</p><ArrowRight /></article>})}</section><section className="work-promise section-wrap"><div><p className="eyebrow">Our promise</p><h2>Good advice is<br /><em>part of the journey.</em></h2></div><div><Sparkles /><p>We will be honest about driving times, permit availability, seasonal trade-offs and the places worth slowing down for. You get the real picture, and a route that can hold it.</p></div></section><EnquiryCta /></main></SiteShell> }
